import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import BootstrapClient from '@/components/BootStrapClient'
import { ToastContainer } from 'react-toastify'

const inter = Inter({ subsets: ['latin'] })
import '@/app/globals.css'
import '@/app/styles.css'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'Auth Task',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
      <html lang='en'>
        <body className={inter.className}>
          {children}
          <BootstrapClient />
          <ToastContainer position='top-center' autoClose={2000} />
        </body>
      </html>
    
  )
}
